# Generated by Django 4.1.4 on 2024-02-05 12:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feature_alter_slider_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='review/')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('ceo', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=100)),
                ('about', tinymce.models.HTMLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
        ),
    ]
